source 'http://rubygems.org'

gem 'bundler'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'haml'
gem 'foreman'
gem 'aws-sdk', github: 'aws/aws-sdk-ruby'
gem 'ruby-opencv'
gem 'rmagick'

gem 'awesome_print'
gem 'racksh'
gem 'debugger'
#gem 'pry'
#gem 'pry-debugger'
